        variable "aws_region" {}
	variable "vpc_name" {}
	variable "vpc_cidr" {}
	variable "public_subnet1_name" {}	
	variable "public_subnet2_name" {}
	variable "public_subnet1_cidr" {}
	variable "public_subnet2_cidr" {}
	variable "private_subnet1_name" {}
	variable "private_subnet2_name" {}
	variable "private_subnet1_cidr" {}
	variable "private_subnet2_cidr" {}
	variable "IGW_name" {}
